name: release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  release:
    if: github.repository == 'jsaguet/eslint-plugin-clean-codestyle'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: yarn

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
